# docker-compose.yml

version: '3.8'
services:
    backend:
      build:
        context: .
        dockerfile: ./docker/Dockerfile.backend
      environment:
        - PYTHONUNBUFFERED=1
      ports:
        - "8000:8000"
      volumes:
        - ./backend:/app
        - ./downloads:/app/downloads
      restart: unless-stopped
